base/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('product/<slug:category_slug>', index, name='categories_by_category'),
    path('about', about, name='aboutus'),
    path('contact', contact, name='contact')
]

commerce/urls.py
from django.urls import path
from . import views

app_name = "commerce"


urlpatterns=[
    path('category', views.categoryList, name='category'),
    path('tag/<slug:tag_slug>', views.categoryList, name='tags_by_tag'),
    path('product/<slug:category_slug>', views.prouctList, name='categories_by_category'),
    path('tag/<slug:tag_slug>', views.prouctList, name='tags_by_tag'),
    path('detail/<str:slug>', views.prodDetails, name='detail'),
    path('addtocart', views.addtocart, name='addtocart'),
    path('cart', views.cart, name='cart'),
    path('updatecart', views.updatecart, name='updatecart'),
    path('remove_item', views.remove_item, name='remove_item'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path('',include('base.urls')),
    path('shop/',include('commerce.urls')),
    path('checkout',include('productcart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.COMPRESS_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cores/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('adminshop/', admin.site.urls),

    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path('',include('base.urls')),
    path('shop/',include('commerce.urls')),
    path('checkout',include('productcart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.COMPRESS_ROOT if getattr(settings, 'COMPRESS_ENABLED', False) else settings.STATIC_ROOT,)

    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

base/models.py
from django.db import models

# Create your models here.

base/views.py
from django.shortcuts import render, get_object_or_404



from commerce.models import *
from productcart.models import *
from dataclasses import dataclass

@dataclass
class G:
    prod = Product.objects.all()
    cat = Category.objects.all()
    cart = ProductCart.objects.all()


def index(request,category_slug= None):
    product = G.prod
    cateogry = None

    if category_slug:
        category = get_object_or_404(Category, slug = category_slug)
        product = G.prod.filter(category=category)[:5]

    return render(request, 'pages/index.html', {"product":product})

def about(request):
    
    return render(request, 'pages/aboutus.html')

def contact(request):
    
    return render(request, 'pages/contact.html')

templates/_base.html
{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home {% block title %} {% endblock title %}</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
    
    <!-- Owl Carousel CSS -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
    />

</head>

<body class="">
    <!-- upper header section -->
    {% block header %}
      
    {% endblock header %}

    <!-- banner section -->
    {% block banner %}
    
    {% endblock banner %}

    <!-- first content -->
    {% block content %}
    
    {% endblock content %}

    <!-- footer section -->    
    {% block footer %}
      
    {% endblock footer %}

    {% comment %} <div class="container mx-auto mt-4">
        {% block content %}
        {% endblock content %}
    </div> {% endcomment %}


    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- Owl Carousel JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.js"></script>
    <script>
        $(document).ready(function(){
            $(".owl-carousel").owlCarousel({
                margin: 30,
                responsiveClass: true,
                nav: true,
                dots: true,
                autoplay: true,
                items: 2,
                fluidSpeed: 200,
                smartSpeed: 1000,
                responsive: {0: {items: 1,},400: {items: 1,},600: {items: 2,}, }
            });

            $('#decrementBtn').click(function (e) {
               e.preventDefault()
                var quantityInput = $('#quantityInput');
                // Decrease the value by 1, but ensure it doesn't go below 0
                quantityInput.val(Math.max(1, parseInt(quantityInput.val()) - 1));
            });

            $('#incrementBtn').click(function (e) {
                e.preventDefault()
                var quantityInput = $('#quantityInput');
                // Increase the value by 1
                quantityInput.val(parseInt(quantityInput.val()) + 1);
            });

            $('#refresh').click(function(e){
                e.preventDefault();
                var prod_id = $(this).closest('.item_data').find('.prod_id').val();
                //var change = $(this).attr('id') === 'decrementBtn' ? -1 : 1;
                //quantityInput.val(Math.max(1, parseInt(quantityInput.val()) + change));

                $.ajax({
                    type: 'POST',
                    url: '{% url "commerce:updatecart" %}',
                    data: {
                        post_id: prod_id,
                        qty_update: $('#quantityInput').val(),
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                        action: 'post'
                    },
                    success: function(json){
                        document.getElementById("price").innerHTML = json['cartsub']
                        document.getElementById("subtotal").innerHTML = json['subtotal']
                        document.getElementById("count").innerHTML = json['qnt']
                        document.getElementById("counts").innerHTML = json['qnt']
                        //var subtotal = $(this).closest('.item_data').find('#subtotal')
                        //subtotal.text(json['cartsub']);
                        //$('#quantityInput').val(json['qnt']);
                        console.log(json)
                    },
                    error: function(rs, e){
                    console.log(rs.error);
                    },
                });
            });

            $('#detailsubmit').click(function(e){
                e.preventDefault();
                var prodid = $("#prodid").val()
                console.log(prodid)
                $.ajax({
                    type: 'POST',
                    url: '{% url "commerce:addtocart" %}',
                    data: {
                        qty_new: $(".quantityInput").val(),
                        prod_id: prodid,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
                        action: 'post'
                    },
                    success: function(response){
                        //document.getElementById("currentqnt").innerHTML = json.qnt
                        alert('Message sent successfully');
                    },
                    error: function(xhr, errmsg, err){
                    console.log(errmsg);
                    },
                });
            });

        });

    </script>
</body>

</html>