base/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('product/<slug:category_slug>', index, name='categories_by_category'),
    path('about', about, name='aboutus'),
    path('contact', contact, name='contact')
]

commerce/urls.py
from django.urls import path
from . import views

app_name = "commerce"


urlpatterns=[
    path('category', views.categoryList, name='category'),
    path('tag/<slug:tag_slug>', views.categoryList, name='tags_by_tag'),
    path('product/<slug:category_slug>', views.prouctList, name='categories_by_category'),
    path('tag/<slug:tag_slug>', views.prouctList, name='tags_by_tag'),
    path('detail/<str:slug>', views.prodDetails, name='detail'),
    path('addtocart', views.addtocart, name='addtocart'),
    path('cart', views.cart, name='cart'),
    path('updatecart', views.updatecart, name='updatecart'),
    path('remove_item', views.remove_item, name='remove_item'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path('',include('base.urls')),
    path('shop/',include('commerce.urls')),
    path('checkout',include('productcart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.COMPRESS_ROOT)

    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

cores/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('adminshop/', admin.site.urls),

    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    path('',include('base.urls')),
    path('shop/',include('commerce.urls')),
    path('checkout',include('productcart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root= settings.COMPRESS_ROOT if getattr(settings, 'COMPRESS_ENABLED', False) else settings.STATIC_ROOT,)

    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

productcart/urls.py
from django.urls import path
from . import views

app_name = "productcart"


urlpatterns=[
    path('', views.checkout, name='checkout'),
]

templates/utils/cart.html
{% extends "_base.html" %}
{% load humanize %}
{% load mathfilters %}



{% load static %}
{% comment %} {% load humanize %} {% endcomment %}


<!-- title section -->
{% block title %} | Cart{% endblock title %}


<!-- upper header section -->
{% block header %}
  {% include "components/navbar.html" %}
{% endblock header %}

<!--content -->
{% block content %}
<div class="mx-auto mt-10 md:mt-5">
    <div class="flex flex-col md:flex-row my-10 md:my-5">
      <div class="md:w-3/4 bg-white px-3 md:px-10 py-10 md:py-5">
        <div class="flex justify-between border-b pb-8">
          <h1 class="font-bold text-2xl md:text-4xl">Cart</h1>
          {% with total_qty=cart|length %}
            {% if total_qty > 0 %}
              <h2 class="font-semibold text-xl md:text-2xl"><span id="count">{{total_qty}}</span> Items</h2>
            {% else %}
              <h2 class="font-semibold text-xl md:text-2xl">0 Items</h2>
            {% endif %}
          {% endwith %}
        </div>
        <div class="flex mt-10 mb-5">
          <h3 class="font-semibold text-gray-600 text-xs uppercase w-2/5">Product Details</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5 text-center">Quantity</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5 text-center">Price</h3>
          <h3 class="font-semibold text-center text-gray-600 text-xs uppercase w-1/5 text-center">Total</h3>
        </div>
        {% for item in cart %}
          {% with items=item.product %}
            <div class="flex items-center hover:bg-gray-100 -mx-8 px-6 py-5">
                  <div class="flex w-2/5"> <!-- product -->
                    <div class="w-20">
                      <img class="h-24" src="{{items.image.url}}" alt="">
                    </div>
                    <div class="flex flex-col justify-between ml-4 flex-grow">
                      <span class="font-bold text-sm">{{items.name}}</span>
                      <span class="text-red-500 text-xs">{{items.category.name}}</span>
                      <form action="{% url 'commerce:remove_item' %}" method="POST">
                        {% csrf_token %}
                            <input type="hidden" name="deletecart" value="{{items.pk}}">
                            <!-- <button type="submit" class=" border-0 bg-transparent text-primary"><small> Delete</small></button> -->
                            <button type="submit" class="font-semibold hover:text-red-500 text-gray-500 text-xs">Remove</button>
                        </form>
                    </div>
                  </div>
                  <div class="flex justify-center w-1/5 relative item_data">
                    <button type="submit" id="decrementBtn">
                      <span id="decrementBtn" class="fill-current text-gray-600 w-3 text-2xl font-thin">-</span>
                    </button>
                    <input type="hidden" class="prod_id" id="prod_id" value="{{items.pk}}">
                    <input id="quantityInput" min="{{items.min_order}}" max="{{items.max_order}}" name="quantity" class="mx-2 border qtn-input w-10" type="text" value="{{item.qnt}}">
                    
                    <button type="submit" class="absolute top-11 right-2/4">
                      <i id="refresh" class="fa-solid fa-arrows-rotate"></i>
                    </button>
                    
                    <button type="submit" id="incrementBtn">
                      <span id="incrementBtn" class="fill-current text-gray-600 w-3 text-2xl font-thin">+</span>
                    </button>
                  </div>
                  <span class="text-center w-1/5 font-semibold text-sm">₦{{items.price|intcomma}}</span>
                  <p class="text-center w-1/5 font-semibold text-sm">₦<span id="price">{{items.price|mul:item.qnt|floatformat:2|intcomma}}</span></p>
            </div>
          {% endwith %}
        {% endfor %}

        <a href="{% url 'commerce:category' %}" class="flex font-semibold text-[#B1250A] text-sm mt-10">
      
          <svg class="fill-current mr-2 text-[#B1250A] w-4" viewBox="0 0 448 512"><path d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"/></svg>
          Continue Shopping
        </a>
      </div>

      <div id="summary" class="md:w-1/4 px-3 md:px-8 py-10 md:py-5">
        <h1 class="font-semibold text-2xl border-b pb-8">Order Summary</h1>
        <div class="flex justify-between mt-10 mb-5">
            {% with total_qty=cart|length %}
              {% if total_qty > 0 %}
                <h1 class="font-semibold text-sm uppercase">Items <span id="counts">{{total_qty}}</span></h1>
              {% else %}
                <span class="font-semibold text-sm uppercase">Items 0</span>
              {% endif %}
            {% endwith %}

            <span class="font-semibold text-sm">₦ <small id="subtotal">{{subtotal|intcomma}}</small></span>
            {% comment %} {% if cart %}
            {% endif %} {% endcomment %}
        </div>
        <div>
          <label class="font-medium inline-block mb-3 text-sm uppercase">Shipping</label>
          <select class="block p-2 text-gray-600 w-full text-sm">
            <option>Standard shipping - $10.00</option>
          </select>
        </div>
        <div class="py-10">
          <label for="promo" class="font-semibold inline-block mb-3 text-sm uppercase">Promo Code</label>
          <input type="text" id="promo" placeholder="Enter your code" class="p-2 text-sm w-full">
        </div>
        <button class="bg-[#B1250A] hover:bg-[#B1250A] px-5 py-2 text-sm text-white uppercase" disabled>Apply</button>
        <div class="border-t mt-8">
          <div class="flex font-semibold justify-between py-6 text-sm uppercase">
            <span>Total cost</span>
            <span>$600</span>
          </div>
          <a href="{% url 'productcart:checkout' %}" class="bg-[#B1250A] px-10 font-semibold hover:bg-[#B1250A] py-3 text-sm text-white uppercase max-w-xl">Checkout</a>
        </div>
      </div>

    </div>
</div>            

{% endblock content %}




<!-- footer content -->
{% block footer %}
  {% include "components/footer.html" %}
{% endblock footer %}

templates/utils/checkout.html
{% extends "_base.html" %}
{% load humanize %}
{% load mathfilters %}



{% load static %}
{% comment %} {% load humanize %} {% endcomment %}


<!-- title section -->
{% block title %} | Checkout{% endblock title %}


<!-- upper header section -->
{% block header %}
  {% include "components/navbar.html" %}
{% endblock header %}

<!--content -->
{% block content %}
<div class="container px-10 pb-20 mx-auto">
    <a href="{% url 'commerce:cart' %}" class="flex font-semibold text-[#B1250A] text-sm mt-10">      
        <svg class="fill-current mr-2 text-[#B1250A] w-4" viewBox="0 0 448 512"><path d="M134.059 296H436c6.627 0 12-5.373 12-12v-56c0-6.627-5.373-12-12-12H134.059v-46.059c0-21.382-25.851-32.09-40.971-16.971L7.029 239.029c-9.373 9.373-9.373 24.569 0 33.941l86.059 86.059c15.119 15.119 40.971 4.411 40.971-16.971V296z"/></svg>
        Continue Shopping
    </a>
  <div class="flex flex-col w-full px-0 mx-auto md:flex-row">
      <div class="flex flex-col md:w-full">
          <h2 class="mb-4 font-bold md:text-3xl text-heading ">Shipping Address
          </h2>
          <form class="justify-center w-full mx-auto" method="post" action>
              <div class="">
                  <div class="space-x-0 lg:flex lg:space-x-4">
                      <div class="w-full lg:w-1/2">
                          <label for="firstName" class="block mb-3 text-sm font-semibold text-gray-500">First
                              Name</label>
                          <input name="firstName" type="text" placeholder="First Name"
                              class="">
                      </div>
                      <div class="w-full lg:w-1/2 ">
                          <label for="firstName" class="block mb-3 text-sm font-semibold text-gray-500">Last
                              Name</label>
                          <input name="Last Name" type="text" placeholder="Last Name"
                              class="">
                      </div>
                  </div>
                  <div class="mt-4">
                      <div class="w-full">
                          <label for="Email"
                              class="block mb-3 text-sm font-semibold text-gray-500">Email</label>
                          <input name="Last Name" type="text" placeholder="Email"
                              class="w-full px-4 py-3 text-sm border border-gray-300 rounded lg:text-sm focus:outline-none focus:ring-1 focus:ring-blue-600">
                      </div>
                  </div>
                  <div class="mt-4">
                      <div class="w-full">
                          <label for="Address"
                              class="block mb-3 text-sm font-semibold text-gray-500">Address</label>
                          <textarea
                              class="w-full px-4 py-3 text-xs border border-gray-300 rounded lg:text-sm focus:outline-none focus:ring-1 focus:ring-blue-600"
                              name="Address" cols="20" rows="4" placeholder="House number and Street name"></textarea>
                      </div>
                  </div>
                  <div class="space-x-0 lg:flex lg:space-x-4">
                      <div class="w-full lg:w-1/2">
                          <label for="city"
                              class="block mb-3 text-sm font-semibold text-gray-500">City</label>
                          <input name="city" type="text" placeholder="City"
                              class="w-full px-4 py-3 text-sm border border-gray-300 rounded lg:text-sm focus:outline-none focus:ring-1 focus:ring-blue-600">
                      </div>
                      <div class="w-full lg:w-1/2 ">
                          <label for="postcode" class="block mb-3 text-sm font-semibold text-gray-500">
                              State</label>
                          <input name="postcode" type="text" placeholder="State"
                              class="w-full px-4 py-3 text-sm border border-gray-300 rounded lg:text-sm focus:outline-none focus:ring-1 focus:ring-blue-600">
                      </div>
                  </div>
                  <div class="flex items-center mt-4">
                      <label class="flex items-center text-sm group text-heading">
                          <input type="checkbox"
                              class="w-5 h-5 border border-gray-300 rounded focus:outline-none focus:ring-1">
                          <span class="ml-2">Save this information for next time</span>
                      </label>
                  </div>
                  <div class="relative pt-3 xl:pt-6"><label for="note"
                          class="block mb-3 text-sm font-semibold text-gray-500"> Notes
                          (Optional)</label><textarea name="note"
                          class="flex items-center w-full px-4 py-3 text-sm border border-gray-300 rounded focus:outline-none focus:ring-1 focus:ring-blue-600"
                          rows="4" placeholder="Notes for delivery"></textarea>
                  </div>
              </div>
          </form>
      </div>
      <div class="flex flex-col w-full ml-0 lg:ml-12 lg:w-2/5">
          <div class="pt-12 md:pt-0 2xl:ps-4">
              <h2 class="text-xl font-bold">Order Summary
              </h2>
              <div class="mt-8">
                    <div class="flex flex-col space-y-4">
                        {% for item in prod %}
                            {% with items=item.product %}
                                <div class="flex space-x-4">
                                    <div>
                                        <img src="{{items.image.url}}" alt="image"
                                            class="w-10">
                                    </div>
                                    <div class="text-xs">
                                        <h2 class="text-sm font-bold">{{items.name}}</h2>
                                        <p class="text-sm">{{items.category.name}}</p>
                                        <span class="text-red-600">Price: </span> ₦{{items.price|mul:item.qnt|floatformat:2|intcomma}}
                                    </div>
                                    <div>
                                        <form action="{% url 'commerce:remove_item' %}" method="POST">
                                        {% csrf_token %}
                                            <input type="hidden" name="deletecart" value="{{items.pk}}">
                                            <!-- <button type="submit" class=" border-0 bg-transparent text-primary"><small> Delete</small></button> -->
                                            <button type="submit">
                                                <svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="none"
                                                    viewBox="0 0 24 24" stroke="currentColor">
                                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                                        d="M6 18L18 6M6 6l12 12" />
                                                </svg>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            {% endwith %}
                        {% endfor %}
                    </div>
              </div>
              <div class="my-2">
                    {% with total_qty=cart|length %}
                        {% if total_qty > 0 %}
                            <h2 class="text-xs font-medium">ITEMS {{total_qty}}</h2>
                        {% else %}
                            <h2 class="text-xs font-medium">ITEMS 0</h2>
                        {% endif %}
                    {% endwith %}
              </div>
              <div>
                <label class="font-medium inline-block mb-3 text-sm uppercase">Shipping</label>
                <select class="block p-2 text-gray-600 w-full text-xm">
                  <option select>Choose your shipping address..</option>
                  <option>Standard shipping - $10.00</option>
                  <option>Standard shipping - $10.00</option>
                  <option>Standard shipping - $10.00</option>
                </select>
              </div>
              <div
                  class="flex items-center w-full py-4 text-sm font-semibold border-b border-gray-300 lg:py-5 lg:px-3 text-heading last:border-b-0 last:text-base last:pb-0">
                  Total<span class="ml-2">₦{{itemtotal}}</span>
              </div>
              <div class="flex items-center mt-2">
                  <label class="flex items-center text-sm group text-heading">
                      <input type="checkbox"
                          class="w-5 h-5 border border-gray-300 rounded focus:outline-none focus:ring-1">
                      <button data-tooltip-target="tooltip-click1" data-tooltip-placement="bottom" data-tooltip-trigger="click" type="button" class="text-black bg-transparent font-medium text-base px-2 py-2.5 my-3 text-center">Direct Bank Transfer</button>
                  </label>
              </div>

              <div class="flex items-center">
                  <label class="flex items-center text-sm group text-heading">
                      <input type="checkbox"
                          class="w-5 h-5 border border-gray-300 rounded focus:outline-none focus:ring-1">
                      <button data-tooltip-target="tooltip-click" data-tooltip-trigger="click" type="button" class="text-black bg-transparent font-medium text-base px-2 py-2.5 my-3 text-center">
                        <img src="{% static '' %}image/payment.png" alt="" width="300" height="300" />
                      </button>
                  </label>
              </div>
              <!-- Show tooltip on click -->
              <div id="tooltip-click1" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-transparent rounded-lg shadow-sm opacity-0 tooltip">
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                hdhfh
                <div class="tooltip-arrow" data-popper-arrow></div>
              </div>
              <div id="tooltip-click" role="tooltip" class="absolute z-10 invisible inline-block px-3 py-2 text-sm font-medium text-white bg-transparent rounded-lg shadow-sm opacity-0 tooltip">
                Tooltip content
                <div class="tooltip-arrow" data-popper-arrow></div>
              </div>
              
              <div class="flex items-center mt-2">
                <P>
                  Your personal data will be used to process your order, 
                  support your experience throughout this website, and for 
                  other purposes described in our privacy policy.
                </p>
              </div>
              <div class="flex items-center mt-2">
                  <label class="flex items-center text-sm group text-heading">
                      <input type="checkbox"
                          class="w-5 h-5 border border-gray-300 rounded focus:outline-none focus:ring-1">
                     I have read and agree to the website terms and conditions *
                  </label>
              </div>
      
              <div class="mt-4">
                <button
                  class="w-full px-6 py-2 text-white bg-[#B1250A] hover:bg-[#B1250A]">Process
                </button>
              </div>
          </div>
      </div>
  </div>
</div>          

{% endblock content %}




<!-- footer content -->
{% block footer %}
  {% include "components/footer.html" %}
{% endblock footer %}